var username;
var myname="Farzeen Shahid";
var message;
message="Hello World";
alert(message);
var uname="Farzeen Shahid";
var age="21 years";
var info="Certified Web application development";
alert(uname);
alert(age);
alert(info);
var pizzaname="PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizzaname);
var email="farzeenshahid50@gmail.com";
var txt="My email address is ";
alert(txt+email);
var mesbox="A smarter way to learn Javascript";
alert(mesbox);
document.writeln("Yah!I can write HTML content through Javascript");
var design="▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
alert(design);
document.writeln("▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬");