let uname = "Farzeen";
let message = "Welcome to our website ";
let banger = "!";
alert(message + uname + banger);
alert("Error! Please enter a valid password");
alert("Welcome to JS Land...\nHappy Coding!");
alert("Welcome to JS Land...");
alert("Happy Coding\n Prevent this page from creating additional dialogs.");
alert("Hello...I can run JS through my web browser's console");
console.log("Hello...I can run JS through my web browser's console");