var age="21 ";
var txt1="I am ";
var txt2="years old";
alert(txt1+age+txt2);
var txt3="You have visited this page 27 times";
var birthyear=2001;
document.writeln("<br>My birth year is "+birthyear+".");
document.writeln("<br>Datatype of my declared variable is number.");
var VisitorsName="Mary Smith";
var ProductTitle="iTWS bluetooth airpods ";
var Quantity="5 ";
document.writeln("<br>"+VisitorsName+" ordered "+Quantity+ProductTitle+" on XYZ clothing store.");
